version: '3'
services:
  info:
      image: nginx:latest
      container_name: appurate-info
      restart: always
      networks:
        - npm_default
      volumes:
        - ./Info/dist:/usr/share/nginx/html:ro
      
  
  app:
    build: ./Front
    container_name: appurate-vite
    volumes:
      - ./Front:/app
      - /app/node_modules
    networks:
      - npm_default
    restart: always

  backend:
    build: ./Back
    container_name: appurate-back
    restart: always
    depends_on:
      - appurate-mongo
    networks:
      - npm_default
      - appurate-local
    volumes:
      - ./Back:/app
      - /app/node_modules

  appurate-mongo:
    image: mongo:latest
    container_name: appurate-mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - appurate-local

  appurate-datamodel:
    container_name: appurate-datamodel
    build: ./Predict
    ports:
      - 5000:5000
    volumes:
      - ./Predict:/app
    networks:
      - appurate-local
      
      
      
networks:
  npm_default:
    name: npm_default
    external: true
  appurate-local:
    name: appurate-local
    external: false

