version: '3'
services:
  frontend:
      image: nginx:latest
      container_name: appurate-front
      restart: always
      networks:
        - npm_default
      ports:
        - 3080:80
        - 3081:443
      volumes:
        - ./Front/dist:/usr/share/nginx/html:ro

  backend:
    build: ./Backend
    container_name: appurate-back
    restart: always
    depends_on:
      - apurate-mongo
    networks:
      - npm_default
      - appurate-local
    volumes:
      - ./Back:/app
      - /app/node_modules

  apurate-mongo:
    image: mongo:latest
    container_name: apurate-mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      - appurate-local

  api:
    build: ./Predict
    container_name: api_data
    ports:
      - 5000:5000
    volumes:
      - ./Predict:/app
    networks:
      - appurate-local
      
      
      
networks:
  npm_default:
    name: npm_default
    external: true
  appurate-local:
    name: appurate-local
    external: false

