version: '3'
services:
  apurate-mongo:
    image: mongo:latest
    container_name: apurate-mongo
    restart: always
    ports:
     - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
  api:
    build: ./Predict
    container_name: api_data
    ports:
      - 5000:5000
    volumes:
      - ./Predict:/app
    

